name: Build

on:
  workflow_call:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        arch: [x64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64
          
    steps:
      - name: Checking out 
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM install
        run: npm ci --arch=${{ matrix.arch }}

      - name: Lint
        run: npm run lint

      - name: Make
        run: npm run make -- --arch=${{ matrix.arch }}

      - name: Test
        run: npm test

      - name: List Generated Files
        run: ls -R ./out/make

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: zip-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ./out/make/zip/darwin/${{ matrix.arch }}/*.zip
            ./out/make/squirrel.windows/${{ matrix.arch }}/*.zip
          compression-level: 0

