name: Build

on:
  workflow_call:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        arch: [x64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64

    steps:
      - name: Checking out 
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM install
        run: npm ci --arch=${{ matrix.arch }}

      - name: Lint
        run: npm run lint

      - name: Make
        run: npm run make -- --arch=${{ matrix.arch }}

      - name: Test
        run: npm test

      - name: List Generated Files
        run: ls -R ./out/make

      - name: Extract macOS Zip
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p ./out/make/extracted
          unzip ./out/make/zip/darwin/${{ matrix.arch }}/*.zip -d ./out/make/extracted

      - name: Ad-Hoc Sign macOS Application
        if: matrix.os == 'macos-latest'
        run: |
          for app in ./out/make/extracted/*.app; do
            echo "Signing $app with Ad-Hoc signature..."
            codesign --sign - --force --deep "$app"
          done

      - name: Re-zip Signed macOS Application
        if: matrix.os == 'macos-latest'
        run: |
          cd ./out/make/extracted
          zip -r ../zip/darwin/${{ matrix.arch }}/AudioVideoMerger-darwin-arm64-2.0.0-signed.zip *.app


      - name: Clean Up Extracted Files
        if: matrix.os == 'macos-latest'
        run: |
          rm -rf ./out/make/extracted

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: zip-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ./out/make/zip/darwin/${{ matrix.arch }}/*.zip
            ./out/make/zip/win32/${{ matrix.arch }}/*.zip
          compression-level: 9
