name: Release

on:
  push:
    brances:
      - dev
    tags:
      - "v*"

jobs:
  build: 
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: List dist directory
        run: ls -R dist
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref, 'beta') }}
          files: |
            dist/zip-macos-latest-arm64/darwin/arm64/*.zip
            dist/zip-macos-latest-x64/darwin/x64/*.zip
            dist/zip-windows-latest-x64/win32/x64/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
